name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t mmilet01/frontend-app-docker-hot-reload -f Dockerfile.dev .

      - name: Run tests in Docker container
        run: docker run -e CI=true mmilet01/frontend-app-docker-hot-reload npm test
# In Create React App, setting CI=true causes the npm test command to run tests once instead of entering watch mode.
